version: '2'
services:
    ipsgateway-mongodb:
        image: mongo:3.4.8
        ports:
            - "27017:27017"
        command: mongos --configdb ipsgateway-mongodb-config
    ipsgateway-mongodb-node:
        build:
            context: .
            dockerfile: mongodb/MongoDB.Dockerfile
        command: mongod --replSet rs1 --noprealloc --smallfiles
    ipsgateway-mongodb-config:
        image: mongo:3.4.8
        container_name: ipsgateway-mongodb-config
        command: mongod --noprealloc --smallfiles --configsvr --dbpath /data/db
